---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(dplyr)

cars = read.csv('/Users/jcaza/Documents/D3/A2/cars-sample.csv')

colors = c('#FF0000', '#CC9900', '#00CC00', '#0066FF', '#CC0099')

cars %>% ggplot(aes(x = Weight, y = MPG, size = Weight, color = Manufacturer)) +
  geom_point(alpha=0.5) + scale_size(range = c(1, 5)) + scale_colour_manual(values = colors)
```

```{r}

colors = c('#33FF00', '#785EF0', '#DC267F', '#FE6100', '#FFB000')

cars %>% ggplot(aes(
  x = Weight, y = MPG, size = Weight, color = Manufacturer)) + 
  geom_point(alpha=0.5) + 
  scale_colour_manual(values = colors) +
  scale_size(range = c(1, 5)) + 
  ggtitle('Car Weight vs MPG') + 
  geom_smooth(method='lm', se=FALSE) +
  facet_wrap(~ Manufacturer) +
  guides(color = FALSE,
         size = guide_legend(override.aes = list(linetype = 0))) +
  theme(legend.position = c(0.85, 0.2), 
        legend.text = element_text(size=10),
        legend.title = element_text(size=13),
        plot.title = element_text(hjust = 0.5, face = 'bold'))
```

